In [1]:
import pandas as pd
import numpy as np

#load iris dataset
dwn_url='https://drive.google.com/uc?id=' + '1C5-s_COuWrjn52wzs-QtEYc6QE_IlR2O'
df = pd.read_csv(dwn_url)

df.head() #membaca 5 baris pertama dari data

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [2]:
# menampilkan unique value pada kolom species
df.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [4]:
df.describe() #menampilkan summary statistic data

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [5]:
# menampilkan jumlah baris dan kolom data
df.shape

(150, 6)

In [6]:
#menghapus kolom id
df = df.drop('Id', axis = 1)

df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
df = df.sample(150).reset_index(drop = True)
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
0              4.6           3.4            1.4           0.3      Iris-setosa
1              5.7           2.6            3.5           1.0  Iris-versicolor
2              5.7           2.9            4.2           1.3  Iris-versicolor
3              4.6           3.2            1.4           0.2      Iris-setosa
4              6.9           3.1            5.1           2.3   Iris-virginica
..             ...           ...            ...           ...              ...
145            5.6           3.0            4.1           1.3  Iris-versicolor
146            5.4           3.9            1.3           0.4      Iris-setosa
147            4.9           3.1            1.5           0.1      Iris-setosa
148            5.9           3.0            5.1           1.8   Iris-virginica
149            4.5           2.3            1.3           0.3      Iris-setosa

[150 rows x 5 columns]

In [8]:
# melakukan fold pada data
fold1 = (df.iloc[0:50].reset_index(drop=True), df.iloc[50:150].reset_index(drop=True))
fold2 = (df.iloc[50:100].reset_index(drop=True), pd.concat([df.iloc[0:50], df.iloc[100:150]]).reset_index(drop=True))
fold3 = (df.iloc[100:150].reset_index(drop=True), df.iloc[0:100].reset_index(drop=True))

test, train = fold2
print(train)

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
0             4.6           3.4            1.4           0.3      Iris-setosa
1             5.7           2.6            3.5           1.0  Iris-versicolor
2             5.7           2.9            4.2           1.3  Iris-versicolor
3             4.6           3.2            1.4           0.2      Iris-setosa
4             6.9           3.1            5.1           2.3   Iris-virginica
..            ...           ...            ...           ...              ...
95            5.6           3.0            4.1           1.3  Iris-versicolor
96            5.4           3.9            1.3           0.4      Iris-setosa
97            4.9           3.1            1.5           0.1      Iris-setosa
98            5.9           3.0            5.1           1.8   Iris-virginica
99            4.5           2.3            1.3           0.3      Iris-setosa

[100 rows x 5 columns]

In [9]:
def norm(df):
  df = (df - df.min()) / (df.max()-df.min())
  return df

X = df.drop('Species',axis=1)
Y = df.Species

X = norm(X)
X

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0         0.083333      0.583333       0.067797      0.083333
1         0.388889      0.250000       0.423729      0.375000
2         0.388889      0.375000       0.542373      0.500000
3         0.083333      0.500000       0.067797      0.041667
4         0.722222      0.458333       0.694915      0.916667
..             ...           ...            ...           ...
145       0.361111      0.416667       0.525424      0.500000
146       0.305556      0.791667       0.050847      0.125000
147       0.166667      0.458333       0.084746      0.000000
148       0.444444      0.416667       0.694915      0.708333
149       0.055556      0.125000       0.050847      0.083333

[150 rows x 4 columns]

In [10]:
#menghitung jarak menggunakan euclidean distance
def euclidean(x1, x2):
  return np.sqrt(np.sum((x1-x2)**2))

#euclidean distance dr data baris pertama dan kedua
euclidean(X.iloc[0], X.iloc[1])

0.6451608221957991

In [15]:
#training knn
def KNN(X_train, y_train, X_test, k):
  dist = []
  #menghitung distance dr data training dan data testing
  for row in range(X_train.shape[0]):
    dist.append(euclidean(X_train.iloc[row], X_test))

  data = X_train.copy()
  data['Dist'] = dist
  data['Class'] = y_train
  data = data.sort_values(by = 'Dist').reset_index(drop=True)
  
  #mengambil label kelas yg sering muncul
  y_pred = data.iloc[:k].Class.mode()
  return y_pred[0]

In [16]:
# menghitung akurasi dari output berdasar kelas
def acc(y_pred, y_true):
  true = 0
  for i in range(len(y_pred)):
    if y_pred[i] == y_true[i]:
      true += 1
  return true/len(y_pred)

In [20]:
#evaluasi mode dg data fold
def evaluate (fold, k):
  test,train = fold
  X_train, y_train = train.drop('Species', axis =1), train.Species
  X_test, y_test = test.drop('Species', axis=1), test.Species
  X_train = norm(X_train)
  X_test = norm(X_test)
  y_preds = []
  for row in range(X_test.shape[0]):
    y_preds.append(KNN(X_train, y_train, X_test.iloc[row], k))

  return (acc(y_preds, y_test))

In [21]:
k = 5
accs = []
folds = [fold1, fold2, fold3]
for i in range(len(folds)):
  accs.append(evaluate(folds[i], k))
print(f'Menggunakan k : {k}, dengan rata-rata akurasi : {sum(accs)/3}')

Menggunakan k : 5, dengan rata-rata akurasi : 0.96