In [1]:
import pandas as pd
import math
import numpy

In [3]:
# membaca data excel
def read_excel(path, sheet_target):
  data = pd.read_excel(path,sheet_name=sheet_target)
  return pd.DataFrame(data)

In [4]:
dataTrain = read_excel("newTrain.xlsx", sheet_target="train")
dataText = read_excel("newTest.xlsx", sheet_target="Sheet1")
dataTruth = read_excel("newTestGroundTruth.xlsx", sheet_target="Sheet1")

In [5]:
#membaca dataTrain
dataTrain

     Unnamed: 0   id  x1  x2  x3  y
0             0    1  83  57  91  1
1             1    2  14  15  88  0
2             2    3  41  12  37  1
3             3    4  16  29  32  0
4             4    5  88  21  18  1
..          ...  ...  ..  ..  .. ..
291         291  292  29  16  27  1
292         292  293  19   2  93  1
293         293  294  68  34  67  0
294         294  295  50  97  15  1
295         295  296  90  16  16  1

[296 rows x 6 columns]

In [6]:
dataText

   Unnamed: 0   id   x1  x2  x3  y
0           0  297   57  85   2  ?
1           1  298   54  66  73  ?
2           2  299   44  31  15  ?
3           3  300   84  23  17  ?
4           4  301  100  81  55  ?
5           5  302   32  52  45  ?
6           6  303   99  15  26  ?
7           7  304   64  81  40  ?
8           8  305   93   9  80  ?
9           9  306   24  67  53  ?

In [7]:
dataTruth

   Unnamed: 0   id  x1  x2  x3  y
0           0  297  82  73  78  1
1           1  298  31  38  68  1
2           2  299  64  91  73  1
3           3  300  33  35  26  0
4           4  301  11  82  30  0
5           5  302  88  26  36  1
6           6  303  22  46  46  1
7           7  304  14  54  12  1
8           8  305  34  54  67  0
9           9  306  98  96  60  0

In [8]:
#melakukan data eksplorasi
dataTrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296 entries, 0 to 295
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  296 non-null    int64
 1   id          296 non-null    int64
 2   x1          296 non-null    int64
 3   x2          296 non-null    int64
 4   x3          296 non-null    int64
 5   y           296 non-null    int64
dtypes: int64(6)
memory usage: 14.0 KB

In [11]:
dataText.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10 non-null     int64
 1   id          10 non-null     int64
 2   x1          10 non-null     int64
 3   x2          10 non-null     int64
 4   x3          10 non-null     int64
 5   y           10 non-null     object
dtypes: int64(5), object(1)
memory usage: 608.0+ bytes

In [12]:
dataTruth.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10 non-null     int64
 1   id          10 non-null     int64
 2   x1          10 non-null     int64
 3   x2          10 non-null     int64
 4   x3          10 non-null     int64
 5   y           10 non-null     int64
dtypes: int64(6)
memory usage: 608.0 bytes

Data Preprocessing

In [13]:
#drop kolom dataset yg tdk diperlukan
dataTrain = dataTrain.drop(["Unnamed: 0"],axis = 1)
dataText = dataText.drop(["Unnamed: 0"], axis =1)
dataTruth = dataTruth.drop(["Unnamed: 0"], axis = 1)

In [14]:
dataTrain.head()

   id  x1  x2  x3  y
0   1  83  57  91  1
1   2  14  15  88  0
2   3  41  12  37  1
3   4  16  29  32  0
4   5  88  21  18  1

In [15]:
dataText.head()

    id   x1  x2  x3  y
0  297   57  85   2  ?
1  298   54  66  73  ?
2  299   44  31  15  ?
3  300   84  23  17  ?
4  301  100  81  55  ?

In [16]:
dataTruth.head()

    id  x1  x2  x3  y
0  297  82  73  78  1
1  298  31  38  68  1
2  299  64  91  73  1
3  300  33  35  26  0
4  301  11  82  30  0

In [17]:
def normalizationMinMax(allData, columnTarget):
  for column in columnTarget:
    allData[column] = (
                      (allData[column] - allData[column].min()) 
                      / allData[column].max() - allData[column].min()
                      )
    return allData

In [18]:
#melakukan combine untuk melakukan normalisasi
testStartID = dataTrain.index.stop

allData = pd.concat([dataTrain, dataText])

allData = normalizationMinMax(allData,['x1','x2','x3'])

normTrain, normTest = allData.iloc[:testStartID].drop('id',axis=1),allData.iloc[testStartID:].drop('id',axis=1)

In [19]:
normTrain

       x1  x2  x3  y
0    0.83  57  91  1
1    0.14  15  88  0
2    0.41  12  37  1
3    0.16  29  32  0
4    0.88  21  18  1
..    ...  ..  .. ..
291  0.29  16  27  1
292  0.19   2  93  1
293  0.68  34  67  0
294  0.50  97  15  1
295  0.90  16  16  1

[296 rows x 4 columns]

In [20]:
normTest

     x1  x2  x3  y
0  0.57  85   2  ?
1  0.54  66  73  ?
2  0.44  31  15  ?
3  0.84  23  17  ?
4  1.00  81  55  ?
5  0.32  52  45  ?
6  0.99  15  26  ?
7  0.64  81  40  ?
8  0.93   9  80  ?
9  0.24  67  53  ?

In [21]:
def standardization(allData, columnTarget):
  for column in columnTarget:
    allData[column] = (allData[column]-allData[column].mean())/(allData[column].std())
  return allData

In [22]:
testStartID = dataTrain.index.stop

allData = pd.concat([dataTrain, dataText])

allData = standardization(allData,['x1','x2','x3'])

stdTrain, stdTest = allData.iloc[:testStartID].drop('id',axis=1),allData.iloc[testStartID:].drop('id',axis=1)

In [23]:
stdTrain

           x1        x2        x3  y
0    1.164512  0.226265  1.440004  1
1   -1.264364 -1.189489  1.337972  0
2   -0.313934 -1.290615 -0.396568  1
3   -1.193961 -0.717571 -0.566621  0
4    1.340518 -0.987239 -1.042769  1
..        ...       ...       ... ..
291 -0.736347 -1.155781 -0.736674  1
292 -1.088358 -1.627699  1.508025  1
293  0.636496 -0.549029  0.623750  0
294  0.002876  1.574603 -1.144801  1
295  1.410920 -1.155781 -1.110790  1

[296 rows x 4 columns]

In [24]:
stdTest

         x1        x2        x3  y
0  0.249284  1.170102 -1.586938  ?
1  0.143680  0.529641  0.827813  ?
2 -0.208331 -0.650154 -1.144801  ?
3  1.199713 -0.919822 -1.076780  ?
4  1.762931  1.035268  0.215623  ?
5 -0.630744  0.057723 -0.124483  ?
6  1.727730 -1.189489 -0.770684  ?
7  0.495691  1.035268 -0.294536  ?
8  1.516523 -1.391740  1.065887  ?
9 -0.912353  0.563350  0.147601  ?

In [26]:
def splitTruth(dataTrain, columnTarget):
  truthData = []
  for truth in dataTrain[columnTarget].unique():
    truthData.append(dataTrain.where(dataTrain[columnTarget]==truth).dropna())
  return truthData

yesData, noData = splitTruth(dataTrain, columnTarget='y')

In [27]:
yesData

        id    x1    x2    x3    y
0      1.0  83.0  57.0  91.0  1.0
2      3.0  41.0  12.0  37.0  1.0
4      5.0  88.0  21.0  18.0  1.0
5      6.0   3.0  18.0  51.0  1.0
7      8.0  11.0   7.0   1.0  1.0
..     ...   ...   ...   ...  ...
290  291.0   6.0  20.0  87.0  1.0
291  292.0  29.0  16.0  27.0  1.0
292  293.0  19.0   2.0  93.0  1.0
294  295.0  50.0  97.0  15.0  1.0
295  296.0  90.0  16.0  16.0  1.0

[151 rows x 5 columns]

In [28]:
noData

        id    x1     x2    x3    y
1      2.0  14.0   15.0  88.0  0.0
3      4.0  16.0   29.0  32.0  0.0
6      7.0  29.0  100.0  14.0  0.0
10    11.0  22.0   36.0  69.0  0.0
14    15.0  40.0   51.0  21.0  0.0
..     ...   ...    ...   ...  ...
283  284.0  48.0   99.0   1.0  0.0
284  285.0  13.0    0.0  23.0  0.0
287  288.0  86.0   48.0  54.0  0.0
288  289.0  83.0   40.0  73.0  0.0
293  294.0  68.0   34.0  67.0  0.0

[145 rows x 5 columns]

In [34]:
def find_mean(yesData, noData, columnTarget):
  yesMean = dict()
  noMean = dict()
  for column in columnTarget:
    yesMean[column] = yesData[column].mean()
    noMean[column] = noData[column].mean()
  return yesMean, noMean

yesMean, noMean = find_mean(yesData, noData, columnTarget=['x1', 'x2', 'x3'])

In [35]:
print(f'Mean Result\n1 : {yesMean}\n0 : {noMean}')

Mean Result
1 : {'x1': 47.95364238410596, 'x2': 48.741721854304636, 'x3': 51.841059602649004}
0 : {'x1': 50.91724137931035, 'x2': 51.84827586206897, 'x3': 45.90344827586207}

In [36]:
def find_std(yesData, noData, columnTarget):
  yesStd = dict()
  noStd = dict()
  for column in columnTarget:
    yesStd[column] = yesData[column].std()
    noStd[column] = noData[column].std()
  return yesStd, noStd

yesStd, noStd = find_std(yesData, noData, columnTarget=['x1', 'x2', 'x3'])

In [37]:
print(f'Standard Deviation Result\n1 : {yesStd}\n0 : {noStd}')

Standard Deviation Result
1 : {'x1': 28.886753076648443, 'x2': 29.63386881619497, 'x3': 29.41475654955786}
0 : {'x1': 27.766512466627617, 'x2': 29.84900217820493, 'x3': 29.42913431210903}

In [38]:
def calc_probality(mean, std, x):

  exponent = math.exp(-((x-mean)**2/(2*std**2)))

  return (1/(math.sqrt(2*math.pi)*std))*exponent

In [40]:
def confussionMatrix(result):

    TP = 0

    FP = 0

    TN = 0

    FN = 0

 

    x = True

 

    for i in result:

        if(i['Ground Truth'] == '?'):

            x = False

            break

        elif((i['Prediction Result'] == 1)and(i['Prediction Result'] == i['Ground Truth'])):

            TP += 1

        elif((i['Prediction Result'] == 0)and(i['Prediction Result'] == i['Ground Truth'])):

            TN += 1

        elif((i['Prediction Result'] == 1)and(i['Prediction Result'] != i['Ground Truth'])):

            FP += 1

        elif((i['Prediction Result'] == 0)and(i['Prediction Result'] != i['Ground Truth'])):

            FN += 1

        

    if(x):

        print(f"\nTP : {TP} FN : {FP}\nTN : {TN} FN : {FN}")

        print(f"Accuracy : {((TP+TN)/(TP+TN+FP+FN))*100}%")

        print(f"Precission : {((TP)/(TP+FP))*100}%")

        print(f"Recall : {((TP)/(TP+FN))*100}%")

    else:

        print("\nCannot process the confussion matrix with unknown Ground Truth!")

In [41]:
def doPrediction(yesMean, yesStd, noMean, noStd, target, columnTarget, truthColumn):

  result = []

  for i in range(len(target)):

    yesResult = 1

    noResult = 1

    for column in columnTarget:

      yesResult *= calc_probality(yesMean[column], yesStd[column], target[column].iloc[i])

      noResult *= calc_probality(noMean[column], noStd[column], target[column].iloc[i])

    result.append({'ID' : target['id'].iloc[i], 'Yes Probability' : "{}".format(yesResult), 'No Probability' : "{}".format(noResult),

                        'Prediction Result' : int(yesResult > noResult), 

                       'Ground Truth' : target[truthColumn].iloc[i]})

  return result

In [43]:
# result

result = []

target = dataText 

 

result = doPrediction(yesMean, yesStd, noMean, noStd, target, columnTarget=['x1','x2','x3'], truthColumn='y')

 

for p in result:

    print(p)

 

confussionMatrix(result)

{'ID': 297, 'Yes Probability': '2.703055728386299e-07', 'No Probability': '4.5075808544073367e-07', 'Prediction Result': 0, 'Ground Truth': '?'}
{'ID': 298, 'Yes Probability': '1.607512382103284e-06', 'No Probability': '1.513301932585517e-06', 'Prediction Result': 1, 'Ground Truth': '?'}
{'ID': 299, 'Yes Probability': '9.531080657381655e-07', 'No Probability': '1.1393103292410503e-06', 'Prediction Result': 0, 'Ground Truth': '?'}
{'ID': 300, 'Yes Probability': '3.9359076167602443e-07', 'No Probability': '4.95396790081609e-07', 'Prediction Result': 0, 'Ground Truth': '?'}
{'ID': 301, 'Yes Probability': '2.734923606379816e-07', 'No Probability': '3.2292622787827514e-07', 'Prediction Result': 0, 'Ground Truth': '?'}
{'ID': 302, 'Yes Probability': '2.094468858775563e-06', 'No Probability': '2.0629990263825832e-06', 'Prediction Result': 1, 'Ground Truth': '?'}
{'ID': 303, 'Yes Probability': '1.8813904672513574e-07', 'No Probability': '2.1581843864443093e-07', 'Prediction Result': 0, 'Ground Truth': '?'}
{'ID': 304, 'Yes Probability': '1.1019747916698164e-06', 'No Probability': '1.4172159083752534e-06', 'Prediction Result': 0, 'Ground Truth': '?'}
{'ID': 305, 'Yes Probability': '1.9234460333525067e-07', 'No Probability': '1.50575323199431e-07', 'Prediction Result': 1, 'Ground Truth': '?'}
{'ID': 306, 'Yes Probability': '1.4777286301728196e-06', 'No Probability': '1.3894897355371137e-06', 'Prediction Result': 1, 'Ground Truth': '?'}

Cannot process the confussion matrix with unknown Ground Truth!

In [44]:
def folding(dataset, trainingPercentage, location, shuffle:bool):

    lengthTraining = int(len(dataset)*trainingPercentage/100)

    # randomize the the data position

    if(shuffle):

        dataset = dataset.sample(frac=1).reset_index(drop=True)

    train = []

    validation = []

    if(location == 'left'):

        train, validation = dataset.iloc[:lengthTraining].reset_index(drop=True), dataset.iloc[lengthTraining:].reset_index(drop=True)

    elif(location == 'right'):

        validation,train = dataset.iloc[:abs(lengthTraining-len(dataset))].reset_index(drop=True), dataset.iloc[abs(lengthTraining-len(dataset)):].reset_index(drop=True)

    elif(location == 'middle'):

        train = dataset.iloc[int(abs(lengthTraining-len(dataset))/2):len(dataset)-int(abs(lengthTraining-len(dataset))/2)]

        validation = pd.concat([dataset.iloc[:int(abs(lengthTraining-len(dataset))/2)],dataset.iloc[len(dataset)-int(abs(lengthTraining-len(dataset))/2):]])

    return train, validation

In [45]:
trainData, validationData = folding(dataTrain.copy(), 70, 'left',shuffle=True)

In [46]:
trainData

      id  x1  x2  x3  y
0    274  13  79  87  1
1    185  30  84  45  1
2    248  21  65  40  1
3    150  19  70   6  1
4    271  83  58  56  1
..   ...  ..  ..  .. ..
202   72  73  14  45  1
203  238  55  33  52  0
204   65  13  47  18  1
205   86  27  61   9  1
206  154  70  96  86  1

[207 rows x 5 columns]

In [47]:
validationData

     id  x1  x2  x3  y
0   133  16  72  68  1
1   220  43  23  66  1
2   218  95  54  54  1
3   132  63  81   5  0
4   162  97  35  51  0
..  ...  ..  ..  .. ..
84  102  31  58  42  0
85    6   3  18  51  1
86  275  64  42  38  0
87  227  98  81   8  0
88  174  46  89  86  0

[89 rows x 5 columns]

In [48]:
yesDataTrain, noDataTrain = splitTruth(trainData, columnTarget='y')
yesDataTrain

        id    x1    x2    x3    y
0    274.0  13.0  79.0  87.0  1.0
1    185.0  30.0  84.0  45.0  1.0
2    248.0  21.0  65.0  40.0  1.0
3    150.0  19.0  70.0   6.0  1.0
4    271.0  83.0  58.0  56.0  1.0
..     ...   ...   ...   ...  ...
199   42.0  63.0  21.0  52.0  1.0
202   72.0  73.0  14.0  45.0  1.0
204   65.0  13.0  47.0  18.0  1.0
205   86.0  27.0  61.0   9.0  1.0
206  154.0  70.0  96.0  86.0  1.0

[111 rows x 5 columns]

In [49]:
noDataTrain

        id    x1    x2    x3    y
8     27.0  24.0  75.0  66.0  0.0
9    155.0  18.0  33.0  15.0  0.0
10   172.0  21.0   1.0  25.0  0.0
13    15.0  40.0  51.0  21.0  0.0
18   243.0  13.0  16.0  17.0  0.0
..     ...   ...   ...   ...  ...
197  115.0  60.0  92.0  66.0  0.0
198   21.0  12.0  17.0  38.0  0.0
200   50.0   8.0  93.0  90.0  0.0
201   33.0  16.0  58.0  94.0  0.0
203  238.0  55.0  33.0  52.0  0.0

[96 rows x 5 columns]

In [50]:
# Split yes and no

yesDataTrain, noDataTrain = splitTruth(trainData, columnTarget='y')

# Find mean

yesMeanTrain, noMeanTrain = find_mean(yesDataTrain, noDataTrain, columnTarget=['x1','x2','x3'])

# Find standard deviation

yesStdTrain, noStdTrain = find_std(yesDataTrain, noDataTrain, ['x1','x2','x3'])

 

result = []

target = validationData # your ground truth data

 

result = doPrediction(yesMeanTrain, yesStdTrain, noMeanTrain, noStdTrain, target, columnTarget=['x1','x2','x3'], truthColumn='y')

 

for p in result:

    print(p)

 

confussionMatrix(result)

{'ID': 133, 'Yes Probability': '8.733332193143207e-07', 'No Probability': '6.968481305460875e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 220, 'Yes Probability': '1.439566275695237e-06', 'No Probability': '1.2992136556786297e-06', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 218, 'Yes Probability': '6.595773709600732e-07', 'No Probability': '6.599420617232517e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 132, 'Yes Probability': '3.602170158488571e-07', 'No Probability': '5.210735385867382e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 162, 'Yes Probability': '5.258881407067624e-07', 'No Probability': '5.177579350403093e-07', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 104, 'Yes Probability': '5.454510870974494e-07', 'No Probability': '4.894804122072291e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 89, 'Yes Probability': '3.873988990342122e-07', 'No Probability': '3.7022510186492436e-07', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 259, 'Yes Probability': '4.822686502849901e-07', 'No Probability': '3.5308134431720827e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 263, 'Yes Probability': '1.2700324345593353e-06', 'No Probability': '1.4059016557465502e-06', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 40, 'Yes Probability': '6.171054595669232e-07', 'No Probability': '7.300207901758736e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 57, 'Yes Probability': '6.644628449000612e-07', 'No Probability': '8.2434771608284e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 224, 'Yes Probability': '2.9449401180808026e-07', 'No Probability': '1.8461075334153392e-07', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 116, 'Yes Probability': '1.3612881541191703e-06', 'No Probability': '1.2093715208938902e-06', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 148, 'Yes Probability': '1.114191309266324e-06', 'No Probability': '1.3385254977173626e-06', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 17, 'Yes Probability': '6.161173046944991e-07', 'No Probability': '4.0415708165803426e-07', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 119, 'Yes Probability': '4.893014153026208e-08', 'No Probability': '5.067626987791595e-08', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 165, 'Yes Probability': '6.349462794252489e-07', 'No Probability': '8.290308672066664e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 161, 'Yes Probability': '1.890038869446189e-07', 'No Probability': '2.851454226368391e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 149, 'Yes Probability': '2.138833874504561e-07', 'No Probability': '2.348564073975253e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 136, 'Yes Probability': '2.6893067451655004e-07', 'No Probability': '2.760388156991856e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 24, 'Yes Probability': '4.5194155415092436e-07', 'No Probability': '5.505094885123737e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 76, 'Yes Probability': '1.2471445112765714e-06', 'No Probability': '1.0649199228519197e-06', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 231, 'Yes Probability': '2.319809388459979e-06', 'No Probability': '2.17886511102715e-06', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 127, 'Yes Probability': '2.260873380260552e-07', 'No Probability': '2.9304018782223397e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 125, 'Yes Probability': '7.063124919001278e-07', 'No Probability': '9.480290716386388e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 194, 'Yes Probability': '1.8258263929262383e-06', 'No Probability': '1.6494633391440877e-06', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 7, 'Yes Probability': '2.049671829974918e-07', 'No Probability': '2.792335892260482e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 63, 'Yes Probability': '2.4791055402614155e-07', 'No Probability': '3.4945537110279126e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 244, 'Yes Probability': '3.122634483839922e-07', 'No Probability': '2.7372922191129123e-07', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 84, 'Yes Probability': '5.322266566595802e-07', 'No Probability': '5.628357186569926e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 178, 'Yes Probability': '1.4188107927818432e-06', 'No Probability': '1.2653525271788828e-06', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 256, 'Yes Probability': '3.213021903945087e-07', 'No Probability': '2.105043692402209e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 206, 'Yes Probability': '1.3037004586759547e-07', 'No Probability': '1.389207840901526e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 101, 'Yes Probability': '5.203637775668883e-07', 'No Probability': '6.451430906225546e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 126, 'Yes Probability': '7.09746387193928e-07', 'No Probability': '5.318870642969684e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 237, 'Yes Probability': '3.3746043674644556e-07', 'No Probability': '3.5964423321721806e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 181, 'Yes Probability': '4.413954043030961e-07', 'No Probability': '3.0058021547225474e-07', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 294, 'Yes Probability': '1.4928181215293987e-06', 'No Probability': '1.428294729092959e-06', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 246, 'Yes Probability': '1.1346911095614773e-06', 'No Probability': '9.167404792591337e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 37, 'Yes Probability': '2.374377501653588e-06', 'No Probability': '2.3766624374103905e-06', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 254, 'Yes Probability': '1.613913439596947e-06', 'No Probability': '1.4010429171965868e-06', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 91, 'Yes Probability': '1.3240659703724732e-06', 'No Probability': '1.3417485257710553e-06', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 284, 'Yes Probability': '1.4310950885672356e-07', 'No Probability': '2.2926680968197667e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 35, 'Yes Probability': '1.3327634827936426e-06', 'No Probability': '1.2137290706280842e-06', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 112, 'Yes Probability': '2.6632623933910275e-07', 'No Probability': '3.3264805361940913e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 80, 'Yes Probability': '1.7838337996946035e-06', 'No Probability': '1.8952782718480813e-06', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 183, 'Yes Probability': '1.2268530666013824e-07', 'No Probability': '1.5480943099689191e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 28, 'Yes Probability': '1.017220129288791e-06', 'No Probability': '1.1649931417562783e-06', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 92, 'Yes Probability': '2.503957548378655e-07', 'No Probability': '2.278506475944859e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 77, 'Yes Probability': '8.894196101634929e-07', 'No Probability': '1.0630457185051212e-06', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 222, 'Yes Probability': '1.4972885365582447e-06', 'No Probability': '1.7449485013325266e-06', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 81, 'Yes Probability': '1.2243432905201187e-06', 'No Probability': '1.057473076306073e-06', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 169, 'Yes Probability': '1.3972702401749847e-06', 'No Probability': '1.4505228521238117e-06', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 85, 'Yes Probability': '5.837676483019273e-07', 'No Probability': '5.853072071824289e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 88, 'Yes Probability': '9.298444410959419e-07', 'No Probability': '8.973580811177623e-07', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 158, 'Yes Probability': '1.9878768859349117e-06', 'No Probability': '1.9155249100822114e-06', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 117, 'Yes Probability': '8.09197422359686e-07', 'No Probability': '8.919853141162325e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 189, 'Yes Probability': '1.1846441529277064e-06', 'No Probability': '8.871942043448793e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 129, 'Yes Probability': '1.13701971174449e-06', 'No Probability': '1.2933083247859402e-06', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 216, 'Yes Probability': '2.666400915304284e-07', 'No Probability': '3.2265879361001367e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 168, 'Yes Probability': '6.739242560788822e-07', 'No Probability': '8.876381784028494e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 94, 'Yes Probability': '1.2946969600357322e-07', 'No Probability': '1.3153106768928557e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 19, 'Yes Probability': '9.521475355852385e-07', 'No Probability': '9.90426150417701e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 11, 'Yes Probability': '1.2620286094672493e-06', 'No Probability': '9.696522921014406e-07', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 261, 'Yes Probability': '1.3615437699045387e-06', 'No Probability': '1.356413944300749e-06', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 288, 'Yes Probability': '1.043755761267731e-06', 'No Probability': '1.0575003955762023e-06', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 56, 'Yes Probability': '4.1833304926013696e-07', 'No Probability': '4.985158839698383e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 103, 'Yes Probability': '1.6759487037456792e-06', 'No Probability': '1.6918510831725192e-06', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 293, 'Yes Probability': '1.6245909819308928e-07', 'No Probability': '1.1804953304347585e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 138, 'Yes Probability': '4.155810128378644e-07', 'No Probability': '4.92776146645009e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 68, 'Yes Probability': '2.347177967702714e-07', 'No Probability': '1.9992429902284557e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 95, 'Yes Probability': '4.225459032222905e-07', 'No Probability': '4.527744580906462e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 46, 'Yes Probability': '9.370652374518438e-07', 'No Probability': '9.844764927586337e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 142, 'Yes Probability': '5.157369516259387e-07', 'No Probability': '7.04454050284899e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 171, 'Yes Probability': '1.7373402102480303e-06', 'No Probability': '1.5559471548693791e-06', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 144, 'Yes Probability': '2.275230310858056e-07', 'No Probability': '1.515364572221424e-07', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 265, 'Yes Probability': '4.3318562806678066e-07', 'No Probability': '3.3709365748382547e-07', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 196, 'Yes Probability': '1.1023365442092976e-06', 'No Probability': '1.1007545156321362e-06', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 223, 'Yes Probability': '1.6243395430261844e-06', 'No Probability': '1.3706308574250152e-06', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 184, 'Yes Probability': '5.199819521617143e-07', 'No Probability': '6.605212740614926e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 249, 'Yes Probability': '9.72416785681607e-07', 'No Probability': '9.313066786228178e-07', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 10, 'Yes Probability': '2.5980191903442094e-07', 'No Probability': '2.6160363293279557e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 111, 'Yes Probability': '1.9221871534145187e-06', 'No Probability': '2.012814132335606e-06', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 108, 'Yes Probability': '7.689694590427846e-07', 'No Probability': '9.267504093328026e-07', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 102, 'Yes Probability': '1.862825666720242e-06', 'No Probability': '1.7848899381730058e-06', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 6, 'Yes Probability': '4.113636059824366e-07', 'No Probability': '2.8948916225434876e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 275, 'Yes Probability': '1.8178755714351752e-06', 'No Probability': '1.9759978466234326e-06', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 227, 'Yes Probability': '1.0983345700710999e-07', 'No Probability': '1.5053198980780254e-07', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 174, 'Yes Probability': '5.39178444286829e-07', 'No Probability': '5.395930508100931e-07', 'Prediction Result': 0, 'Ground Truth': 0}

TP : 18 FN : 20
TN : 29 FN : 22
Accuracy : 52.80898876404494%
Precission : 47.368421052631575%
Recall : 45.0%

In [52]:
result = []

target = dataText # your ground truth data

 

result = doPrediction(yesMeanTrain, yesStdTrain, noMeanTrain, noStdTrain, target, columnTarget=['x1','x2','x3'], truthColumn='y')

 

for p in result:

    print(p)

 

confussionMatrix(result)

{'ID': 297, 'Yes Probability': '2.8651603690601637e-07', 'No Probability': '4.2542525087080127e-07', 'Prediction Result': 0, 'Ground Truth': '?'}
{'ID': 298, 'Yes Probability': '1.6277778734472986e-06', 'No Probability': '1.5669307209916147e-06', 'Prediction Result': 1, 'Ground Truth': '?'}
{'ID': 299, 'Yes Probability': '9.272157669291045e-07', 'No Probability': '1.0531361777558649e-06', 'Prediction Result': 0, 'Ground Truth': '?'}
{'ID': 300, 'Yes Probability': '3.8419006500956255e-07', 'No Probability': '4.633316898904133e-07', 'Prediction Result': 0, 'Ground Truth': '?'}
{'ID': 301, 'Yes Probability': '2.8182801957002733e-07', 'No Probability': '3.077211056894782e-07', 'Prediction Result': 0, 'Ground Truth': '?'}
{'ID': 302, 'Yes Probability': '2.028670588652634e-06', 'No Probability': '1.901480330914932e-06', 'Prediction Result': 1, 'Ground Truth': '?'}
{'ID': 303, 'Yes Probability': '1.8136232009548423e-07', 'No Probability': '2.040456260625972e-07', 'Prediction Result': 0, 'Ground Truth': '?'}
{'ID': 304, 'Yes Probability': '1.097694859373458e-06', 'No Probability': '1.3471038325743499e-06', 'Prediction Result': 0, 'Ground Truth': '?'}
{'ID': 305, 'Yes Probability': '1.8869489043817693e-07', 'No Probability': '1.7352676901958364e-07', 'Prediction Result': 1, 'Ground Truth': '?'}
{'ID': 306, 'Yes Probability': '1.4572251526698698e-06', 'No Probability': '1.3016875296297746e-06', 'Prediction Result': 1, 'Ground Truth': '?'}

Cannot process the confussion matrix with unknown Ground Truth!

In [55]:
exerciseData = pd.read_csv("Naive-Bayes-Classification-Data.csv")
exerciseData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 995 entries, 0 to 994
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   glucose        995 non-null    int64
 1   bloodpressure  995 non-null    int64
 2   diabetes       995 non-null    int64
dtypes: int64(3)
memory usage: 23.4 KB

In [56]:
exerciseData.describe()

          glucose  bloodpressure    diabetes
count  995.000000     995.000000  995.000000
mean    44.306533      79.184925    0.500503
std      6.707567       9.340204    0.500251
min     20.000000      50.000000    0.000000
25%     40.000000      72.000000    0.000000
50%     45.000000      80.000000    1.000000
75%     50.000000      87.000000    1.000000
max     70.000000     100.000000    1.000000

In [57]:
exerciseData.head()

   glucose  bloodpressure  diabetes
0       40             85         0
1       40             92         0
2       45             63         1
3       45             80         0
4       40             73         1

In [58]:
id = [i for i in range(len(exerciseData))]
exerciseData['id']=id

In [59]:
rescaledData = standardization(exerciseData, columnTarget=['glucose','bloodpressure'])
rescaledData.head()

    glucose  bloodpressure  diabetes  id
0 -0.642041       0.622585         0   0
1 -0.642041       1.372034         0   1
2  0.103386      -1.732823         1   2
3  0.103386       0.087265         0   3
4 -0.642041      -0.662183         1   4

In [61]:
# Training
trainData, testData = folding(rescaledData, trainingPercentage=80, location='left', shuffle=True)
trainData

      glucose  bloodpressure  diabetes   id
0    0.103386      -0.662183         1  560
1   -0.642041      -0.233927         1  852
2    0.848813      -0.233927         1  535
3    0.848813      -1.839888         1  406
4   -0.642041       0.943778         0  494
..        ...            ...       ...  ...
791 -0.642041       0.622585         0   33
792 -0.642041       0.836714         0  330
793 -0.642041       0.622585         0  534
794 -0.642041       0.836714         0  827
795 -1.387468       0.408457         0  463

[796 rows x 4 columns]

In [62]:
testData

      glucose  bloodpressure  diabetes   id
0    0.103386       0.622585         0  758
1   -0.642041      -2.054016         1  993
2    0.103386      -0.233927         1  519
3    0.103386      -0.126863         1  324
4    0.848813       0.408457         0  447
..        ...            ...       ...  ...
194 -1.387468       0.087265         1   14
195 -0.642041      -0.983375         1  273
196 -0.642041       0.836714         0   71
197 -0.642041       1.479098         0  112
198 -0.642041      -0.448055         1  188

[199 rows x 4 columns]

In [63]:
yesData, noData = splitTruth(trainData, columnTarget='diabetes')
yesData

      glucose  bloodpressure  diabetes     id
0    0.103386      -0.662183       1.0  560.0
1   -0.642041      -0.233927       1.0  852.0
2    0.848813      -0.233927       1.0  535.0
3    0.848813      -1.839888       1.0  406.0
5    1.594239      -1.197503       1.0  332.0
..        ...            ...       ...    ...
783  1.594239      -1.518695       1.0  512.0
784 -2.132894      -0.126863       1.0   80.0
785 -0.642041       0.622585       1.0   92.0
786  0.848813       0.087265       1.0  246.0
788  0.103386      -0.448055       1.0  166.0

[406 rows x 4 columns]

In [64]:
noData

      glucose  bloodpressure  diabetes     id
4   -0.642041       0.943778       0.0  494.0
7   -0.642041       0.943778       0.0  445.0
8    0.103386       0.408457       0.0  320.0
9    1.594239       1.479098       0.0  766.0
12   0.103386       0.622585       0.0  197.0
..        ...            ...       ...    ...
791 -0.642041       0.622585       0.0   33.0
792 -0.642041       0.836714       0.0  330.0
793 -0.642041       0.622585       0.0  534.0
794 -0.642041       0.836714       0.0  827.0
795 -1.387468       0.408457       0.0  463.0

[390 rows x 4 columns]

In [65]:
yesMean, noMean = find_mean(yesData, noData, columnTarget=['glucose', 'bloodpressure'])
yesMean

{'glucose': -0.0012676886494671466, 'bloodpressure': -0.7993093961188249}

In [66]:
noMean

{'glucose': -0.017029269996927027, 'bloodpressure': 0.8010255516904956}

In [67]:
yesStd, noStd = find_std(yesData, noData, columnTarget=['glucose', 'bloodpressure'])
yesStd

{'glucose': 1.3350011236792412, 'bloodpressure': 0.6612293457485487}

In [68]:
noStd

{'glucose': 0.5641703550097849, 'bloodpressure': 0.4818315145149308}

In [69]:
result = []

target = testData

 

result = doPrediction(yesMean, yesStd, noMean, noStd, target, columnTarget=['glucose', 'bloodpressure'], truthColumn='diabetes')

 

for p in result:

    print(p)

 

confussionMatrix(result)

{'ID': 758, 'Yes Probability': '0.01780464186821269', 'No Probability': '0.534368389728149', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 993, 'Yes Probability': '0.02655159491302897', 'No Probability': '7.531917443964386e-09', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 519, 'Yes Probability': '0.12470797384379696', 'No Probability': '0.05698595765666023', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 324, 'Yes Probability': '0.10717037473776134', 'No Probability': '0.08960385844191378', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 447, 'Yes Probability': '0.027763682003149426', 'No Probability': '0.12939347263738', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 217, 'Yes Probability': '0.00042440712061384114', 'No Probability': '0.11774970701679309', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 889, 'Yes Probability': '0.01780464186821269', 'No Probability': '0.534368389728149', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 584, 'Yes Probability': '0.004976952624869453', 'No Probability': '0.3033517767167873', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 270, 'Yes Probability': '0.06592300371447461', 'No Probability': '7.071472562091218e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 50, 'Yes Probability': '0.0020111703958500247', 'No Probability': '0.24092408268562138', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 507, 'Yes Probability': '0.004976952624869453', 'No Probability': '0.3033517767167873', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 928, 'Yes Probability': '0.005567439815218076', 'No Probability': '0.5477244805384819', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 219, 'Yes Probability': '0.11148134481265604', 'No Probability': '0.03156110803384286', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 987, 'Yes Probability': '0.0022497843521942363', 'No Probability': '0.4350065770717131', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 756, 'Yes Probability': '0.06592300371447461', 'No Probability': '7.071472562091218e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 126, 'Yes Probability': '0.00013194988816248417', 'No Probability': '0.05707759411746673', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 374, 'Yes Probability': '0.1545728900667662', 'No Probability': '0.00033330532123975024', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 925, 'Yes Probability': '0.10717037473776134', 'No Probability': '0.08960385844191378', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 511, 'Yes Probability': '0.1499353388623045', 'No Probability': '0.00010515085182831083', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 424, 'Yes Probability': '0.00014760499372618724', 'No Probability': '0.10305789511680717', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 15, 'Yes Probability': '0.14161639258417433', 'No Probability': '0.00018962298720643113', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 414, 'Yes Probability': '0.0022497843521942363', 'No Probability': '0.4350065770717131', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 419, 'Yes Probability': '0.10717037473776134', 'No Probability': '0.08960385844191378', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 513, 'Yes Probability': '0.01780464186821269', 'No Probability': '0.534368389728149', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 557, 'Yes Probability': '0.004559778085872045', 'No Probability': '0.17258191336837062', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 36, 'Yes Probability': '0.0022497843521942363', 'No Probability': '0.4350065770717131', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 716, 'Yes Probability': '0.10993922200772857', 'No Probability': '1.286054030923012e-05', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 505, 'Yes Probability': '0.14705888694768088', 'No Probability': '0.0008907686134583087', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 728, 'Yes Probability': '0.08639440674706168', 'No Probability': '9.857989148188247e-05', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 945, 'Yes Probability': '0.00013194988816248417', 'No Probability': '0.05707759411746673', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 350, 'Yes Probability': '0.0022497843521942363', 'No Probability': '0.4350065770717131', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 420, 'Yes Probability': '0.08639440674706168', 'No Probability': '9.857989148188247e-05', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 244, 'Yes Probability': '0.0020111703958500247', 'No Probability': '0.24092408268562138', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 934, 'Yes Probability': '0.00014760499372618724', 'No Probability': '0.10305789511680717', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 912, 'Yes Probability': '0.1795573133067484', 'No Probability': '0.002827038862670608', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 134, 'Yes Probability': '0.005567439815218076', 'No Probability': '0.5477244805384819', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 3, 'Yes Probability': '0.0731607421902712', 'No Probability': '0.1910363788964382', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 581, 'Yes Probability': '0.030303783960396187', 'No Probability': '0.2274383164145517', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 169, 'Yes Probability': '0.0731607421902712', 'No Probability': '0.1910363788964382', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 31, 'Yes Probability': '0.12279825110518164', 'No Probability': '3.3131868020584005e-05', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 422, 'Yes Probability': '0.1545728900667662', 'No Probability': '0.00033330532123975024', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 751, 'Yes Probability': '0.16051331876706135', 'No Probability': '0.001565727463916564', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 57, 'Yes Probability': '0.01458214520713164', 'No Probability': '0.16837355718004973', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 982, 'Yes Probability': '0.10993922200772857', 'No Probability': '1.286054030923012e-05', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 645, 'Yes Probability': '0.005567439815218076', 'No Probability': '0.5477244805384819', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 40, 'Yes Probability': '0.13403307500005868', 'No Probability': '5.8236757455212325e-05', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 337, 'Yes Probability': '0.027763682003149426', 'No Probability': '0.12939347263738', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 715, 'Yes Probability': '0.027763682003149426', 'No Probability': '0.12939347263738', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 887, 'Yes Probability': '0.10505463108355738', 'No Probability': '0.0001513275770298964', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 479, 'Yes Probability': '0.1278390834497075', 'No Probability': '0.006262603318484295', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 460, 'Yes Probability': '0.005567439815218076', 'No Probability': '0.5477244805384819', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 441, 'Yes Probability': '0.13423460316114677', 'No Probability': '4.0815590827771224e-05', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 326, 'Yes Probability': '0.004976952624869453', 'No Probability': '0.3033517767167873', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 696, 'Yes Probability': '0.00047476061744299567', 'No Probability': '0.21260596462418', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 336, 'Yes Probability': '0.014586635876668995', 'No Probability': '2.356160839031657e-10', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 688, 'Yes Probability': '0.004976952624869453', 'No Probability': '0.3033517767167873', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 180, 'Yes Probability': '0.00042440712061384114', 'No Probability': '0.11774970701679309', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 82, 'Yes Probability': '0.033899155987505925', 'No Probability': '0.4106570103560345', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 305, 'Yes Probability': '0.033899155987505925', 'No Probability': '0.4106570103560345', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 243, 'Yes Probability': '0.001842591519181297', 'No Probability': '0.13706575124240275', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 871, 'Yes Probability': '0.019833574365347533', 'No Probability': '0.0219819158442041', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 108, 'Yes Probability': '0.1545728900667662', 'No Probability': '0.00033330532123975024', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 283, 'Yes Probability': '0.012486234175684976', 'No Probability': '2.7890322208062426e-10', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 896, 'Yes Probability': '0.09580379771711131', 'No Probability': '0.049626209207065626', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 650, 'Yes Probability': '0.014586635876668995', 'No Probability': '2.356160839031657e-10', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 811, 'Yes Probability': '0.1729120864463953', 'No Probability': '0.0006018078611986956', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 438, 'Yes Probability': '0.08491762815731703', 'No Probability': '1.0426573992460228e-05', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 357, 'Yes Probability': '0.033899155987505925', 'No Probability': '0.4106570103560345', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 383, 'Yes Probability': '0.0449715501125994', 'No Probability': '0.3342984051065612', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 227, 'Yes Probability': '0.00014760499372618724', 'No Probability': '0.10305789511680717', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 274, 'Yes Probability': '0.004976952624869453', 'No Probability': '0.3033517767167873', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 690, 'Yes Probability': '0.0022497843521942363', 'No Probability': '0.4350065770717131', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 25, 'Yes Probability': '0.028941262158350457', 'No Probability': '6.7854401541278105e-09', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 358, 'Yes Probability': '0.10213683580595222', 'No Probability': '0.017955643680279878', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 325, 'Yes Probability': '0.01730302109774773', 'No Probability': '1.5119841380072694e-08', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 189, 'Yes Probability': '0.042804576650509116', 'No Probability': '0.010225919680373195', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 660, 'Yes Probability': '0.008420424788512806', 'No Probability': '0.5707305755007602', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 893, 'Yes Probability': '0.036832062042343794', 'No Probability': '0.105333722408326', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 629, 'Yes Probability': '0.030303783960396187', 'No Probability': '0.2274383164145517', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 253, 'Yes Probability': '0.08818111838027155', 'No Probability': '4.897963583008708e-05', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 435, 'Yes Probability': '0.00042440712061384114', 'No Probability': '0.11774970701679309', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 708, 'Yes Probability': '0.01458214520713164', 'No Probability': '0.16837355718004973', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 2, 'Yes Probability': '0.06635098857029206', 'No Probability': '5.655244800031774e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 340, 'Yes Probability': '0.01780464186821269', 'No Probability': '0.534368389728149', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 646, 'Yes Probability': '0.07296361225318927', 'No Probability': '0.003050381447096306', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 17, 'Yes Probability': '0.1199975720842184', 'No Probability': '2.2605310580927948e-05', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 817, 'Yes Probability': '0.0731607421902712', 'No Probability': '0.1910363788964382', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 165, 'Yes Probability': '0.08777340077358302', 'No Probability': '0.028233182712394105', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 901, 'Yes Probability': '0.008420424788512806', 'No Probability': '0.5707305755007602', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 718, 'Yes Probability': '0.1545728900667662', 'No Probability': '0.00033330532123975024', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 693, 'Yes Probability': '0.15609014073384894', 'No Probability': '0.019875669949919784', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 225, 'Yes Probability': '0.008420424788512806', 'No Probability': '0.5707305755007602', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 781, 'Yes Probability': '0.00042440712061384114', 'No Probability': '0.11774970701679309', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 983, 'Yes Probability': '0.09945525603878459', 'No Probability': '5.303032855074375e-06', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 642, 'Yes Probability': '0.01458214520713164', 'No Probability': '0.16837355718004973', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 200, 'Yes Probability': '0.10993922200772857', 'No Probability': '1.286054030923012e-05', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 141, 'Yes Probability': '0.0731607421902712', 'No Probability': '0.1910363788964382', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 85, 'Yes Probability': '0.14161639258417433', 'No Probability': '0.00018962298720643113', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 775, 'Yes Probability': '0.033899155987505925', 'No Probability': '0.4106570103560345', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 431, 'Yes Probability': '0.000900019399166702', 'No Probability': '2.3513887109872294e-14', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 304, 'Yes Probability': '0.04884276526968212', 'No Probability': '9.187727182185308e-08', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 384, 'Yes Probability': '0.10717037473776134', 'No Probability': '0.08960385844191378', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 517, 'Yes Probability': '0.1278390834497075', 'No Probability': '0.006262603318484295', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 782, 'Yes Probability': '0.03004603248273852', 'No Probability': '8.089700406211483e-05', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 760, 'Yes Probability': '0.06540125443044509', 'No Probability': '0.10580360567196591', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 378, 'Yes Probability': '0.0449715501125994', 'No Probability': '0.3342984051065612', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 968, 'Yes Probability': '0.001842591519181297', 'No Probability': '0.13706575124240275', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 868, 'Yes Probability': '0.00752734769384536', 'No Probability': '0.31609347446829383', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 627, 'Yes Probability': '0.06635098857029206', 'No Probability': '5.655244800031774e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 776, 'Yes Probability': '0.15609014073384894', 'No Probability': '0.019875669949919784', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 777, 'Yes Probability': '0.14161639258417433', 'No Probability': '0.00018962298720643113', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 872, 'Yes Probability': '0.004976952624869453', 'No Probability': '0.3033517767167873', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 43, 'Yes Probability': '0.10717037473776134', 'No Probability': '0.08960385844191378', 'Prediction Result': 1, 'Ground Truth': 0}
{'ID': 948, 'Yes Probability': '0.05991923757729315', 'No Probability': '0.06019344572749285', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 724, 'Yes Probability': '0.054341994471459515', 'No Probability': '1.7819049592168832e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 335, 'Yes Probability': '0.08890695077588441', 'No Probability': '2.9370322045725807e-06', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 271, 'Yes Probability': '0.0731607421902712', 'No Probability': '0.1910363788964382', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 981, 'Yes Probability': '0.15609014073384894', 'No Probability': '0.019875669949919784', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 457, 'Yes Probability': '0.0022497843521942363', 'No Probability': '0.4350065770717131', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 745, 'Yes Probability': '0.0022497843521942363', 'No Probability': '0.4350065770717131', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 138, 'Yes Probability': '0.10292603105072362', 'No Probability': '0.00030457262225415925', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 890, 'Yes Probability': '0.005567439815218076', 'No Probability': '0.5477244805384819', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 658, 'Yes Probability': '0.00081862057184675', 'No Probability': '0.283568741301169', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 515, 'Yes Probability': '0.1545728900667662', 'No Probability': '0.00033330532123975024', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 298, 'Yes Probability': '0.005567439815218076', 'No Probability': '0.5477244805384819', 'Prediction Result': 0, 'Ground Truth': 1}
{'ID': 299, 'Yes Probability': '0.10213683580595222', 'No Probability': '0.017955643680279878', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 261, 'Yes Probability': '0.13953509358432867', 'No Probability': '0.011007942874521597', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 470, 'Yes Probability': '0.11148134481265604', 'No Probability': '0.03156110803384286', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 428, 'Yes Probability': '0.0036108379083619837', 'No Probability': '4.774065757382197e-14', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 794, 'Yes Probability': '0.1545728900667662', 'No Probability': '0.00033330532123975024', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 10, 'Yes Probability': '0.10292603105072362', 'No Probability': '0.00030457262225415925', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 64, 'Yes Probability': '0.01780464186821269', 'No Probability': '0.534368389728149', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 343, 'Yes Probability': '0.030303783960396187', 'No Probability': '0.2274383164145517', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 731, 'Yes Probability': '0.0022497843521942363', 'No Probability': '0.4350065770717131', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 149, 'Yes Probability': '0.011982707742976589', 'No Probability': '1.6753111367478032e-10', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 813, 'Yes Probability': '0.048477223101431585', 'No Probability': '5.433298726032373e-07', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 672, 'Yes Probability': '0.09132455731592169', 'No Probability': '0.001063917802858209', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 877, 'Yes Probability': '0.00752734769384536', 'No Probability': '0.31609347446829383', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 778, 'Yes Probability': '0.01780464186821269', 'No Probability': '0.534368389728149', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 686, 'Yes Probability': '0.015916267085392954', 'No Probability': '0.2959546381530298', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 250, 'Yes Probability': '0.015245557126394754', 'No Probability': '8.851571955199782e-10', 'Prediction Result': 1, 'Ground Truth': 1}
{'ID': 625, 'Yes Probability': '0.01458214520713164', 'No Probability': '0.16837355718004973', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 884, 'Yes Probability': '0.01780464186821269', 'No Probability': '0.534368389728149', 'Prediction Result': 0, 'Ground Truth': 0}
{'ID': 939, 'Yes Probability': '0.0022497843521942363', 'No Probability': '0.4350065770717131', 'Prediction Result': 0, 'Ground Truth': 0}

In [70]:
for i in trainData.id:
  print(i)

560
852
535
406
494
332
79
445
320
766
249
411
197
139
805
927
212
485
67
355
131
171
848
122
806
222
865
545
220
399
543
509
284
104
245
701
704
78
121
175
120
572
684
333
295
559
976
208
988
278
203
860
380
975
408
129
886
522
18
588
214
586
653
664
140
172
677
682
338
145
59
487
558
668
481
654
692
209
651
910
815
321
86
240
293
521
157
611
830
234
571
547
251
48
750
801
711
153
434
703
954
518
375
570
845
361
949
732
77
842
93
965
16
752
977
874
191
984
429
127
553
41
461
606
951
809
533
883
154
256
173
410
182
415
467
644
30
544
765
882
593
187
941
914
772
706
933
123
247
749
423
947
288
617
754
277
932
238
499
847
810
695
940
486
656
985
989
425
443
311
659
492
719
90
615
831
239
47
853
51
155
878
347
737
371
211
838
774
387
833
897
961
530
532
393
575
257
53
873
524
674
98
821
349
462
739
474
501
829
603
937
146
381
764
561
342
854
267
309
626
87
717
89
514
705
826
788
959
316
133
218
784
768
855
91
563
125
198
5
648
351
747
516
880
620
605
639
193
730
707
614
964
38
52
292
523
453
290
580
259
471
318
174
404
888
510
75
599
368
229
744
159
594
390
498
637
266
280
628
837
26
661
170
490
666
101
562
195
683
676
662
459
20
681
363
898
841
743
400
34
952
413
483
328
793
151
923
109
537
859
590
360
269
294
32
960
69
679
578
128
427
905
301
451
597
622
162
892
861
402
302
306
444
23
364
241
206
943
464
909
168
213
808
700
773
795
143
797
680
178
740
536
612
488
587
771
9
955
344
99
339
598
876
792
667
401
607
317
623
748
770
237
967
440
669
585
421
418
94
272
331
389
391
583
569
539
591
285
601
226
156
556
260
329
83
386
264
297
73
638
891
65
105
966
907
327
124
573
68
834
843
844
671
60
935
702
62
973
640
224
223
137
365
262
382
106
416
720
392
528
709
7
780
712
741
367
228
452
286
807
803
480
102
978
791
694
54
636
118
592
836
727
450
405
835
113
713
150
938
352
502
201
456
863
577
755
858
904
287
787
114
407
70
263
641
194
111
319
555
296
254
221
117
376
29
714
632
366
657
248
531
942
489
574
44
116
980
736
35
72
689
496
958
412
946
373
698
971
633
432
761
465
526
746
359
369
525
334
956
96
922
144
652
759
388
279
184
190
281
969
825
924
345
950
4
433
610
624
448
742
757
832
322
769
994
691
181
403
409
370
323
1
215
846
504
313
252
255
953
738
919
974
354
449
823
538
231
911
186
635
916
930
567
542
13
307
472
12
647
158
564
314
160
851
397
979
540
468
789
242
643
22
167
276
913
944
88
798
862
568
869
258
495
6
753
875
185
204
822
183
136
291
589
800
147
454
315
426
491
903
176
466
906
856
477
142
675
24
699
783
21
312
722
879
864
990
763
548
100
308
177
649
920
500
439
554
493
45
986
152
576
346
527
926
710
356
436
437
95
417
503
103
396
600
630
27
850
115
37
110
74
991
957
377
723
541
446
931
385
66
970
289
631
870
799
735
917
867
395
49
866
148
310
725
885
881
107
46
812
232
767
76
634
655
802
482
497
796
963
199
665
857
602
918
621
372
908
902
442
475
816
478
275
205
779
729
579
235
818
820
687
673
300
549
828
566
929
697
11
992
550
726
341
58
900
565
8
962
216
81
484
915
604
268
210
282
824
899
42
804
663
618
430
790
894
895
119
236
61
230
97
849
552
551
508
161
130
921
56
619
476
972
819
512
80
92
246
164
166
721
596
33
330
534
827
463